// apps/nuxt/components/Footer.vue
<script setup lang="ts"></script>

<template>
  <footer
    class="p-2 text-center text-sm text-gray-500 bg-gray-100 mx-auto backdrop-blur-sm">
    with <span class="text-red-500">❤</span> by
    <a
      href="https://me.alexandergekov.com"
      target="_blank"
      rel="noopener noreferrer"
      class="text-gray-700 hover:text-gray-900 transition-colors underline">
      Alexander Gekov
    </a>
    <span class="mx-2">·</span>
    <a
      href="https://github.com/alexandergekov/ziip.fun/blob/main/LICENSE"
      target="_blank"
      rel="noopener noreferrer"
      class="text-gray-700 hover:text-gray-900 transition-colors underline">
      MIT License
    </a>
  </footer>
</template>

// src/components/Footer.tsx
const Footer = () => {
  return (
    <footer className="p-2 text-center text-sm text-gray-500 bg-gray-100 mx-auto backdrop-blur-sm">
      with <span className="text-red-500">❤</span> by{" "}
      <a
        href="https://me.alexandergekov.com"
        target="_blank"
        rel="noopener noreferrer"
        className="text-gray-700 hover:text-gray-900 transition-colors underline">
        Alexander Gekov
      </a>
      <span className="mx-2">·</span>
      <a
        href="https://github.com/alexandergekov/ziip.fun/blob/main/LICENSE"
        target="_blank"
        rel="noopener noreferrer"
        className="text-gray-700 hover:text-gray-900 transition-colors underline">
        MIT License
      </a>
    </footer>
  );
};

export default Footer;
